### ISSUE TITLE
Support ARM architectures

### ISSUE THREAD

**Issue by noraworld** [Ryooooooga/zabrze#1]
I wanted to install zabrze to my Raspberry Pi 4, but it failed because it did not support ARM architectures, only support x86_64 architectures.

Could you please support ARM architectures version?

**Comment by Ryooooooga** [comment]
I have prepared binaries for aarch64, although I have not confirmed that it works.
https://github.com/Ryooooooga/zabrze/releases/tag/v0.1.6+2

**Comment by noraworld** [comment]
Thank you!

I will try it from right now, and let you know how it is.

**Comment by noraworld** [comment]
It seems to work for me, including the following features.

* Hit the enter key without a trailing space
* `^X` to avoid expanding
* Global abbreviations (`global: true` options)
* Abbreviations with contexts (`context` options)
* Auto-expand arithmetic expansions (`evaluate: true` options)

Thank you for your quick response and support 🙏
