### ISSUE TITLE
Split config file

### ISSUE THREAD

**Issue by noraworld** [Ryooooooga/zabrze#15]
My zabrze config file is getting long and hard to read. I’d like to split the config file into some, but how can I do that? If it’s impossible for now, do you have a plan to implement this?

**Comment by Ryooooooga** [comment]
@noraworld Currently not possible.
I'm willing to support multiple config files and have some ideas, but they all have advantages and disadvantages..

1. adding `include` directive to `config.yaml`:

  ```yaml
  include:
    - ./**/*.yaml
   ```

2. `ZSH_CONFIG_FILE` with multiple paths separated by colons:

```sh
export ZABRZE_CONFIG_FILE="$XDG_CONFIG_HOME/zabrze/config.yaml:$XDG_CONFIG_HOME/zabrze/conf.d/*.yaml"
```

3. simply reads all YAML files under `$XDG_CONFIG_HOME/zabrze/`

**Comment by noraworld** [comment]
So, what are pros and cons for each approach?

**Comment by Ryooooooga** [comment]
1. It is troublesome to prevent multiple reads considering physical and logical paths.
2. Require users to configure cumbersome settings.
3. The order in which each file is read is not self-explanatory.

I think it would be better to fix the reading order of `3` in dictionary order.

**Comment by noraworld** [comment]
I see. I’m afraid I haven’t come up with other good ideas, but I think the first one looks great for me. But as you pointed out, if you have a hard time implementing this way, I think the third one of a dictionary order is another good option.

**Comment by Ryooooooga** [comment]
implemented `3.`. https://github.com/Ryooooooga/zabrze/pull/14

**Comment by noraworld** [comment]
Great job! Thank you for supporting. 🙏

Should I put some files under `~/.config/zabrze/` instead of `~/.config/zabrze/config.yaml` to use this feature?
